### ISSUE TITLE
Ability to select by double click

### ISSUE THREAD

**Issue by nin-jin** [qntm/base2048#23]
Some code points breaks the words, which does not allow user to select the entire text by double click/tap.

Example: 
```
ЭइໃݹƐಬໃݲЭॴເɕநՋໂڥѻටҽݤߜටԮڍஸق൱ݹࠅ৩ບݔƐഠഉٽॳඝಽٽࠌҼຯڤߜ૪ଞ1
```

**Comment by qntm** [comment]
Probably what's needed here is a button you can just tap to copy the replay to the clipboard. I should be able to provide that today.

**Comment by qntm** [comment]
Oh, I guess you raised this against `base2048`, not `hatetris`... in that case we have a more interesting conundrum. I think it might be fairly difficult in the general case to determine where the browser inserts these breaks. Having determined that, I think it might be possible to insert non-breaking joiners or something in the gap to make the browser consider the entire string to be double-clickable... I'm not sure, I would have to check. But the real problem is that inserting those extra characters alters the string. It would no longer be Base2048. And we would no longer have the "1 Twitter character of output per 11 bits of input" guarantee.

Base64 suffers from the same issue due to its use of "+" and "/". I think this isn't a problem to be solved in the encoding itself but in the presentation layer. I'll add that "Copy replay to clipboard" button to HATETRIS and consider that sufficient I think.

**Comment by qntm** [comment]
So double-clicking doesn't work in the way you requested, but [you will find](https://qntm.org/files/hatetris/hatetris.html) we now have a dedicated "copy replay" button. I hope this meets your needs.

**Comment by nin-jin** [comment]
It's better to use code points that just don't break the words... It's actual for copy from twitter/messanger.

**Comment by nin-jin** [comment]
https://unicode.org/reports/tr29/#Word_Boundaries

**Comment by qntm** [comment]
Did some further number crunching. Among the 4,352 "light" characters, there are only 2,026 with favourable Word_Break properties, whereas we need 2,056.

Cheers...

**Comment by nin-jin** [comment]
Thank you for the research!
