### ISSUE TITLE
What about emojis?

### ISSUE THREAD

**Issue by juancroldan** [qntm/base2048#35]
If the goal is to fit as much text as possible in a tweet, why not using emojis as well?

**Comment by qntm** [comment]
Good thought. You are describing another encoding which already exists: [Ecoji](https://github.com/keith-turner/ecoji).

* Ecoji encodes 10 bits per emoji * 140 emoji per Tweet / 8 bits per byte = 175 bytes per Tweet.
* Base2048 encodes 11 bits per character * 280 characters per Tweet / 8 bits per byte = 385 bytes per Tweet, which is more than twice as efficient.

**Comment by juancroldan** [comment]
I see. My suggestions was using both Base2048 characters and emojis, rather then only emojis.

**Comment by qntm** [comment]
The efficiency gains from that would be negligible because emoji are so large (effectively twice the size of a Base2048 character) and there are so few of them.

Base2048 encodes 22 bits per 2 characters. Let's say we wanted to increase that to 23 bits per 2 characters, by adding emoji. We would need 2^22 ~= 4,000,000 emoji to do this. However, there are only approximately 1000-2000 of them.

**Comment by juancroldan** [comment]
Oh, so an emoji counts as two characters on Twitter, I was missing that piece of info.

Got it, thanks! 🙂
